# Generated by Django 3.2.18 on 2023-03-08 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.URLField(db_index=True, help_text='The host that the node is served from', max_length=128)),
                ('username', models.CharField(db_index=True, help_text='Username used for node-to-node communication', max_length=32)),
                ('password', models.CharField(help_text='Password used for node-to-node communication', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
