# Generated by Django 3.2.18 on 2023-03-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_node_api_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='api_prefix',
        ),
        migrations.AddField(
            model_name='node',
            name='api_path',
            field=models.CharField(default='/api/posts', max_length=128),
        ),
    ]
