# Generated by Django 3.2.18 on 2023-03-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_node_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='api_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
