# Generated by Django 3.2.18 on 2023-03-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='id',
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.URLField(max_length=128, primary_key=True, serialize=False, verbose_name='author who is following the followee'),
        ),
    ]
