# Generated by Django 3.2.18 on 2023-03-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0001_initial_squashed_0004_auto_20230323_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
