# Generated by Django 3.2.18 on 2023-03-23 18:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follower', '0002_alter_follower_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='follower_node_id',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('follower_node_id', 'followee')},
        ),
    ]
