# Generated by Django 3.2.18 on 2023-03-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0002_auto_20230314_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.URLField(db_index=True, max_length=128, primary_key=True, serialize=False, verbose_name='author who is following the followee'),
        ),
    ]
