# Generated by Django 3.2.18 on 2023-03-23 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follower', '0003_alter_follower_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.URLField(db_index=True, max_length=128, verbose_name='author who is following the followee'),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('follower', 'followee')},
        ),
    ]
