# Generated by Django 3.2.18 on 2023-03-02 20:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0003_auto_20230221_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.URLField(max_length=128)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Published At')),
                ('comment', models.TextField()),
                ('content_type', models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain Text')], max_length=32, verbose_name='Content Type')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name="Post's id")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
