# Generated by Django 3.2.18 on 2023-03-22 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('post', '0001_initial'), ('post', '0002_auto_20230221_0336'), ('post', '0003_auto_20230221_0520'), ('post', '0004_category'), ('post', '0005_alter_category_id'), ('post', '0006_alter_category_options')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.URLField(default='http://localhost:8000', help_text='The node that created the post', max_length=128)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Published At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('rev', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0, verbose_name='Total Comment Count')),
                ('like_count', models.IntegerField(default=0, verbose_name='Total Like Count')),
                ('unlisted', models.BooleanField(default=False, help_text='Does this post appear in authors streams')),
                ('visibility', models.CharField(choices=[('FRIENDS', 'Friends'), ('PUBLIC', 'Public')], help_text='Who can view this post', max_length=16)),
                ('origin', models.URLField(default='http://localhost:8000', help_text='The node that created the post', max_length=128)),
                ('source', models.URLField(default='http://localhost:8000', help_text='The node that shared the post', max_length=128)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain Text'), ('application/base64', 'Base64'), ('image/png;base64', 'PNG Image'), ('image/jpeg;base64', 'JPEG Image')], max_length=32, verbose_name='Content Type')),
                ('description', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Owner's Author Id")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='post', max_length=128, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
