# Generated by Django 3.2.18 on 2023-02-21 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='host',
            field=models.URLField(default='http://localhost', help_text='The node that created the post', max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://localhost', help_text='The node that created the post', max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://localhost', help_text='The node that shared the post', max_length=128),
        ),
    ]
