# Generated by Django 3.2.18 on 2023-02-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20230221_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='host',
            field=models.URLField(default='http://localhost:8000', help_text='The node that created the post', max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://localhost:8000', help_text='The node that created the post', max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://localhost:8000', help_text='The node that shared the post', max_length=128),
        ),
    ]
