# Generated by Django 3.1.6 on 2023-02-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20230216_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(help_text='The node that created the post', max_length=128),
        ),
    ]
