# Generated by Django 3.2.18 on 2023-03-18 20:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20230221_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categories', models.CharField(blank=True, default='post', max_length=128, verbose_name='Categories')),
                ('category_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Category Items')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
