# Generated by Django 3.2.18 on 2023-03-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_content'),
        ('post', '0006_alter_category_options'),
    ]

    operations = [
    ]
