# Generated by Django 3.2.18 on 2023-03-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
