# Generated by Django 3.2.18 on 2023-03-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('post', '0003_auto_20230221_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.URLField(db_index=True, max_length=128, verbose_name='Who liked it')),
                ('context', models.URLField(choices=[('https://www.w3.org/ns/activitystreams', 'W3 Activity Streams')], default='https://www.w3.org/ns/activitystreams', max_length=128)),
                ('summary', models.CharField(max_length=128)),
                ('liked_at', models.DateTimeField(auto_now_add=True, verbose_name='Liked At')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comment.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post')),
            ],
            options={
                'unique_together': {('author', 'post', 'comment')},
            },
        ),
    ]
