# Generated by Django 3.2.18 on 2023-03-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='context',
            field=models.URLField(choices=[('https://www.w3.org/ns/activitystreams', 'W3 Activity Streams')], default='https://www.w3.org/ns/activitystreams', max_length=128),
        ),
    ]
