# Generated by Django 3.2.18 on 2023-03-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_like_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.UUIDField(),
        ),
    ]
