# Generated by Django 3.2.18 on 2023-03-17 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_alter_like_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Published At'),
            preserve_default=False,
        ),
    ]
