# Generated by Django 3.1.6 on 2023-02-14 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField()),
                ('rev', models.IntegerField(default=0)),
                ('displayName', models.CharField(default='', max_length=128)),
                ('github', models.URLField(default='', max_length=128)),
                ('host', models.URLField(max_length=128)),
                ('profileImage', models.URLField(default='', max_length=128)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
