# Generated by Django 3.1.6 on 2023-02-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(default='', max_length=128, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(default='', max_length=128, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(default='', max_length=128, verbose_name='Profile Image'),
        ),
    ]
