# Generated by Django 3.1.6 on 2023-02-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, default='', max_length=128, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, default='', max_length=128, verbose_name='Profile Image'),
        ),
    ]
