# Generated by Django 3.1.6 on 2023-02-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20230214_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation On'),
        ),
        migrations.AlterField(
            model_name='author',
            name='lastModified',
            field=models.DateTimeField(verbose_name='Last Modified On'),
        ),
    ]
