# Generated by Django 3.2.18 on 2023-02-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20230221_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://localhost:8000', max_length=128),
        ),
    ]
