# Generated by Django 3.1.6 on 2023-02-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20230214_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified On'),
        ),
    ]
