# Generated by Django 3.2.18 on 2023-03-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://localhost:8000', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Profile Image'),
        ),
    ]
