# Generated by Django 3.2.18 on 2023-02-18 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('object_id', models.URLField(max_length=128, verbose_name='Object Node ID')),
                ('sender_author_id', models.URLField(max_length=128, verbose_name='Object Sender Author Node ID')),
                ('context', models.URLField(choices=[('https://www.w3.org/ns/activitystreams', 'W3 Activity Streams')], default='https://www.w3.org/ns/activitystreams', max_length=128)),
                ('summary', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('post', 'Post'), ('like', 'Like'), ('follow_request', 'Follow Request'), ('comment', 'Comment')], default='post', max_length=32)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Inbox Author's UUID")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
