# Generated by Django 3.2.18 on 2023-03-12 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inbox', '0002_auto_20230221_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Inbox Owner'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='sender_author_id',
            field=models.URLField(max_length=128, verbose_name='Object From'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='summary',
            field=models.CharField(max_length=128),
        ),
    ]
