# Generated by Django 3.2.18 on 2023-03-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_auto_20230312_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='object_id',
            field=models.URLField(max_length=512, verbose_name='Object Node ID'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='sender_author_id',
            field=models.URLField(max_length=512, verbose_name='Object From'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='summary',
            field=models.CharField(max_length=512),
        ),
    ]
