# Generated by Django 3.2.18 on 2023-03-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_auto_20230324_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('like', 'Like'), ('follow', 'Follow Request'), ('comment', 'Comment')], default='post', max_length=32),
        ),
    ]
