name: Django CI Run Tests
env:
  PROJECT_PATH: api/
  DJANGO_ALLOWED_HOSTS: testserver
  DJANGO_CORS_ORIGIN_ALLOW_ALL: False
  DJANGO_CORS_ORIGIN_WHITELIST: 'http://localhost:3000'
  DJANGO_DEBUG: True
  DJANGO_LOG_LEVEL: INFO
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

on:
  push:
    branches: [ "dev", "master" ]
    paths: 'api/**'
  pull_request:
    branches: [ "dev", "master" ]
    paths: 'api/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python Dependencies
      run: |
        cd $PROJECT_PATH
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run All Django Tests
      run: |
        cd $PROJECT_PATH
        python manage.py test
