# 2023-02-21
# workflows/run_react_tests.yml

# This code is modified from a tutorial article from GitHub, retrieved 2023-02-21 at docs.github.com
# Tutorial article here:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI Run Tests
env:
  PROJECT_PATH: ui/
  CI: false

on:
  push:
    branches: [ "dev", "master" ]
    paths: 'ui/**'
  pull_request:
    branches: [ "dev", "master" ]
    paths: 'ui/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json
    - run: |
        cd $PROJECT_PATH
        npm ci
        npm run build --if-present
        npm test
